### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mini' of undefined

### ISSUE THREAD

**Issue by kassemsandarusi** [atom/command-palette#24]
Uncaught TypeError: Cannot read property 'mini' of undefined

**Atom Version**: 0.155.0
**System**: linux 3.13.0-40-generic
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.30.0

### Steps To Reproduce

1. Open command palette
2. select Editor: attached

Note: I had been toying with the settings page and then switched to an editor. I was searching editor in the keybindings filter (doubt its related though).

### Stack Trace

```
At /usr/share/atom/resources/app/src/workspace-view.js:93

TypeError: Cannot read property 'mini' of undefined
  at atom-workspace.attachedCallback (/usr/share/atom/resources/app/src/workspace-view.js:93:24)
  at atom-workspace.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by kevinsawicki** [comment]
The `Editor: Attached` command was incorrectly in the command palette and that has since been fixed, closing this out.
