### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by sbromberger** [atom/command-palette#25]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.156.0
**System**: Mac OS X 10.10.1
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.30.0
### Steps To Reproduce
1. Invoke command palette
2. Select "Window: Log Deprecation Warnings"
### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:275

TypeError: undefined is not a function
  at atom-workspace.atom.commands.add.window:log-deprecation-warnings (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:275:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

Also ref https://github.com/atom/atom/issues/4486

**Comment by jberube** [comment]
Got the same bug, with a different command. The bug reporter think its the same as this one.

# Steps to reproduce

1. Open command palette
2. Type `previous word`
3. Select `Editor: Move to previous Word`

**Atom Version**: 0.177.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.34.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At c:\Users\jberube-dev\AppData\Local\atom\app-0.177.0\resources\app\src\text-editor-element.js:339

TypeError: undefined is not a function
  at TextEditor.atom.commands.add.stopEventPropagation.editor:move-to-previous-word (c:\Users\jberube-dev\AppData\Local\atom\app-0.177.0\resources\app\src\text-editor-element.js:339:19)
  at atom-text-editor.newCommandListeners.(anonymous function) (c:\Users\jberube-dev\AppData\Local\atom\app-0.177.0\resources\app\src\text-editor-element.js:286:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\jberube-dev\AppData\Local\atom\app-0.177.0\resources\app\src\command-registry.js:243:29)
  at c:\Users\jberube-dev\AppData\Local\atom\app-0.177.0\resources\app\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (c:\Users\jberube-dev\AppData\Local\atom\app-0.177.0\resources\app\node_modules\command-palette\lib\command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (c:\Users\jberube-dev\AppData\Local\atom\app-0.177.0\resources\app\node_modules\command-palette\node_modules\atom-space-pen-views\lib\select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (c:\Users\jberube-dev\AppData\Local\atom\app-0.177.0\resources\app\node_modules\command-palette\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\jberube-dev\AppData\Local\atom\app-0.177.0\resources\app\src\command-registry.js:243:29)
  at c:\Users\jberube-dev\AppData\Local\atom\app-0.177.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (c:\Users\jberube-dev\AppData\Local\atom\app-0.177.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (c:\Users\jberube-dev\AppData\Local\atom\app-0.177.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (c:\Users\jberube-dev\AppData\Local\atom\app-0.177.0\resources\app\src\window-event-handler.js:170:20)

```

### Commands

```
  2x -0:38.9 core:backspace (atom-text-editor.editor.mini)
     -0:34.6 core:confirm (atom-text-editor.editor.mini)
     -0:34.5 core:focus-previous (atom-text-editor.editor)
     -0:32.8 command-palette:toggle (atom-text-editor.editor)
     -0:29.3 core:confirm (atom-text-editor.editor.mini)
     -0:29.3 core:focus-previous (atom-text-editor.editor)
     -0:27.5 command-palette:toggle (atom-text-editor.editor)
     -0:24.8 core:confirm (atom-text-editor.editor.mini)
     -0:24.8 core:focus-previous (atom-text-editor.editor)
     -0:23.7 command-palette:toggle (atom-text-editor.editor)
     -0:21.6 core:confirm (atom-text-editor.editor.mini)
     -0:21.6 core:focus-previous (atom-text-editor.editor)
     -0:20.2 command-palette:toggle (atom-text-editor.editor)
  2x -0:17.5 core:move-down (atom-text-editor.editor.mini)
     -0:13.3 core:confirm (atom-text-editor.editor.mini)
     -0:13.3 editor:move-to-previous-word (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "projectHome": "c:\\dev\\git\\",
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by kalanosh** [comment]
1. Open command palette
1. Type previous word
1. Select Editor: Move to previous Word

**Atom Version**: 0.200.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.36.0


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\src\text-editor-element.js:345

TypeError: undefined is not a function
  at TextEditor.atom.commands.add.stopEventPropagation.editor:move-to-previous-word (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\src\text-editor-element.js:345:19)
  at atom-text-editor.newCommandListeners.(anonymous function) (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\src\text-editor-element.js:286:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\src\window-event-handler.js:178:20)

```

### Commands

```
     -0:51.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  5x -0:48.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:44.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:44.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:44.4.0 editor:move-to-previous-word (atom-text-editor.editor)
     -0:41.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:41 core:move-down (atom-text-editor.editor.is-focused)
     -0:12.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 17x -0:10.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:08.2.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:07.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:05.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:02.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.6.0 editor:move-to-previous-word (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
linter, v0.12.4
linter-coffeelint, v0.2.3
linter-csslint, v0.0.12
linter-htmlhint, v0.0.15
linter-jshint, v0.1.4
linter-less, v0.4.0
linter-php, v0.0.12
linter-pylint, v0.2.1
linter-rubocop, v0.2.6
script, v2.23.0

# Dev
No dev packages
```
