### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'webkitMatchesSelector' on 'Element': '0' is not a valid selector.

### ISSUE THREAD

**Issue by M1Reeder** [atom/command-palette#30]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.179.0
**System**: Mac OS X 10.9.3
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.34.0

### Stack Trace

Uncaught SyntaxError: Failed to execute 'webkitMatchesSelector' on 'Element': '0' is not a valid selector.

```
At /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:117

Error: Failed to execute 'webkitMatchesSelector' on 'Element': '0' is not a valid selector.
  at Error (native)
  at CommandRegistry.module.exports.CommandRegistry.findCommands (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:117:121)
  at CommandPaletteView.module.exports.CommandPaletteView.show (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:70:32)
  at CommandPaletteView.module.exports.CommandPaletteView.toggle (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:49:21)
  at atom-workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:21:21)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:172:20)

```

### Commands

```
  4x -4:00.6 core:undo (atom-text-editor.editor.is-focused)
     -0:00.4 command-palette:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "sublime-tabs",
      "linter-coffeelint"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
coffee-lint, v0.7.3
color-picker, v1.4.4
file-icons, v1.4.8
highlight-selected, v0.8.0
jsformat, v0.7.18
jshint, v1.2.0
language-marko, v0.4.8
linter, v0.10.0
pain-split, v1.2.0
project-manager, v1.14.1

# Dev
No dev packages
```

**Comment by NM-** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.34.0

### Stack Trace

Uncaught SyntaxError: Failed to execute 'webkitMatchesSelector' on 'Element': '0' is not a valid selector.

```
At /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:117

Error: Failed to execute 'webkitMatchesSelector' on 'Element': '0' is not a valid selector.
  at Error (native)
  at CommandRegistry.module.exports.CommandRegistry.findCommands (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:117:121)
  at CommandPaletteView.module.exports.CommandPaletteView.show (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:70:32)
  at CommandPaletteView.module.exports.CommandPaletteView.toggle (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:49:21)
  at atom-workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:21:21)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:00.7 command-palette:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
linter, v0.12.0
minimap, v4.3.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@M1Reeder @NM- could you please share some reproduction steps for how to trigger this error?  Is this reproducible in safe mode (`atom --safe`)?

**Comment by NM-** [comment]
@M1Reeder this is NM-. . . My Bad!  For the delay. . .I really thought i put in the steps to reproduce this error but I see i clearly must have missed that step.  However, here is the steps that i had to redo.  Only thing is when i did redo i got this error?

Steps taken was open atom to trigger the latest code for the ascii-art:convert.
reload the page then pull up the cmd palet.  Then load the ascii-art:convert.  

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.34.0

### Stack Trace

Uncaught SyntaxError: Failed to execute 'webkitMatchesSelector' on 'Element': '0' is not a valid selector.

```
At /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:117

Error: Failed to execute 'webkitMatchesSelector' on 'Element': '0' is not a valid selector.
  at Error (native)
  at CommandRegistry.module.exports.CommandRegistry.findCommands (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:117:121)
  at CommandPaletteView.module.exports.CommandPaletteView.show (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:70:32)
  at CommandPaletteView.module.exports.CommandPaletteView.toggle (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:49:21)
  at atom-workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:21:21)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:00.7 command-palette:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
linter, v0.12.0
minimap, v4.3.1

# Dev
No dev packages
```

**Comment by despairblue** [comment]
Is there any way to fix this without building atom from master? Even after disabling color-picker, linter and minimap (the packages listed in the last crash report), changing the theme and the syntax theme it happens every time, which renders atom practically useless :cry:

It does not happen with `atom --safe` I just simply don't know which package is causing this, since trying to bisect this breaks package cop.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: linux 3.14.26-1-lts
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.34.0

### Stack Trace

Uncaught SyntaxError: Failed to execute 'webkitMatchesSelector' on 'Element': '0' is not a valid selector.

```
At /usr/share/atom/resources/app/src/command-registry.js:117

Error: Failed to execute 'webkitMatchesSelector' on 'Element': '0' is not a valid selector.
  at Error (native)
  at CommandRegistry.module.exports.CommandRegistry.findCommands (/usr/share/atom/resources/app/src/command-registry.js:117:121)
  at CommandPaletteView.module.exports.CommandPaletteView.show (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:70:32)
  at CommandPaletteView.module.exports.CommandPaletteView.toggle (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:49:21)
  at atom-workspace.<anonymous> (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:21:21)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at __bind (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:01.8 command-palette:toggle (div.settings-view.pane-item)
     -0:00.4 AtomPair:hide views (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "autocomplete",
      "incremental-search",
      "Tern",
      "grunt-runner",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "atomatigit",
      "linter-scspell",
      "open-plus",
      "atom-ternjs",
      "minimap-highlight-selected",
      "minimap-git-diff",
      "minimap-find-and-replace",
      "minimap-color-highlight",
      "minimap",
      "color-picker",
      "linter",
      "linter-coffeelint",
      "linter-eslint",
      "linter-htmlhint",
      "linter-js-yaml",
      "linter-jshint",
      "linter-puppet-lint",
      "linter-shellcheck"
    ],
    "projectHome": "/home/despairblue/vcs/git/",
    "destroyEmptyPanes": false,
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-alignment, v0.11.0
atom-color-highlight, v3.0.8
atom-pair, v0.37.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.0
autocomplete-snippets, v1.0.1
block-cursor, v0.8.1
block-travel, v1.0.2
bug-report, v0.6.2
compare-files, v0.4.1
docblockr, v0.6.3
editorconfig, v0.3.0
file-icons, v1.5.0
filetype-color, v0.1.4
git-log, v0.3.0
go-plus, v3.2.3
grammar-token-limit, v0.1.1
highlight-selected, v0.9.1
indentation-indicator, v0.4.1
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.8
language-dockerfile, v0.1.0
language-haskell, v1.0.0
language-latex, v0.4.1
language-nimrod, v0.1.0
language-puppet, v0.10.0
language-tss, v0.0.2
markdown-scroll-sync, v0.1.0
navigate, v0.0.10
open-last-project, v0.3.4
package-cop, v0.2.4
project-manager, v1.15.5
regex-railroad-diagram, v0.7.1
symbols-tree-view, v0.6.1
tab-smart-sort, v0.1.2
tabs-to-spaces, v0.8.1
test-status, v0.27.1
zentabs, v0.8.2

# Dev
autocomplete-plus, v2.0.2
```

**Comment by despairblue** [comment]
For anyone else unable to use atom because of this, this fixes it for me:

```diff
--- /usr/share/atom/resources/app/src/command-registry.js       2015-03-06 11:25:53.849187272 +0100
+++ /usr/share/atom/resources/app/src/command-registry.js       2015-03-06 11:23:52.679041528 +0100
@@ -114,7 +114,7 @@
           listeners = _ref2[commandName];
           for (_i = 0, _len = listeners.length; _i < _len; _i++) {
             listener = listeners[_i];
-            if (typeof currentTarget.webkitMatchesSelector === "function" ? currentTarget.webkitMatchesSelector(listener.selector) : void 0) {
+            if (Number.isNaN(Number.parseInt(listener.selector)) && typeof currentTarget.webkitMatchesSelector === "function" ? currentTarget.webkitMatchesSelector(listener.selector) : void 0) {
               if (!commandNames.has(commandName)) {
                 commandNames.add(commandName);
                 commands.push({
```

**Comment by chodorowicz** [comment]
@despairblue thanks! that helps... I also wasn't able to execute any command from command palette because of this

**Comment by oliverox** [comment]
@despairblue Yes this fixes the issue. Can this be checked in as a PR?

**Comment by despairblue** [comment]
Looks like https://github.com/atom/atom/issues/5828 is also fixing this, and probably in a less hacky way.
