### ISSUE TITLE
Uncaught Error: Cannot find module './git-log-view'

### ISSUE THREAD

**Issue by theprophet31337** [atom/command-palette#31]
[Enter steps to reproduce below:]

1. open root git folder
2. open build.gradle
3. Ctrl-Shift-P then select "Git Log: Show"

**Atom Version**: 0.184.0
**System**: Microsoft Windows 8 Enterprise
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.34.0

### Stack Trace

Uncaught Error: Cannot find module './git-log-view'

```
At module.js:353

Error: Cannot find module './git-log-view'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\src\module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at C:\Users\theprophet31337\.atom\packages\git-log\lib\git-log.js:46:30
  at wrappedOpener (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\src\workspace.js:578:16)
  at Workspace.module.exports.Workspace.openURIInPane (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\src\workspace.js:495:22)
  at Workspace.module.exports.Workspace.open (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\src\workspace.js:428:19)
  at atom-workspace.<anonymous> (C:\Users\theprophet31337\.atom\packages\git-log\lib\git-log.js:26:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\src\command-registry.js:243:29)
  at C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\node_modules\command-palette\lib\command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\src\command-registry.js:243:29)
  at C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\src\window-event-handler.js:182:20)

```

### Commands

```
     -7:53.1 application:open-folder (atom-pane.pane.active)
     -4:22.4 project-find:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:15.0 core:confirm (atom-text-editor.editor.mini)
     -3:45.6 core:cancel (atom-pane.pane.active)
     -3:35.7 fuzzy-finder:toggle-git-status-finder (atom-pane.pane.active)
     -2:31.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-atom-dark-ui)
     -2:28.2 core:confirm (atom-text-editor.editor.mini)
     -0:17.6 command-palette:toggle (atom-pane.pane.active)
  2x -0:14.9 core:move-down (atom-text-editor.editor.mini)
     -0:10.6 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:10.6 core:cancel (atom-text-editor.editor.mini)
     -0:06.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.9 core:move-down (atom-text-editor.editor.mini)
     -0:03.4 core:move-up (atom-text-editor.editor.mini)
     -0:03.3 core:confirm (atom-text-editor.editor.mini)
     -0:03.3 git-log:show (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
git-projects, v1.8.1
language-gradle, v0.0.3
language-groovy, v0.3.0
linter, v0.12.0
linter-javac, v0.1.3
seti-syntax, v0.3.3
text-manipulation, v0.4.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Looks like the `git-log` package isn't cleaning up properly after itself after it gets uninstalled.

**Comment by 50Wliu** [comment]
This issue was moved to NikhilKalige/git-log#48
