### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'webkitMatchesSelector' on 'Element': 'coffee-lint:lint-current-file' is not a valid selector.

### ISSUE THREAD

**Issue by atalargo** [atom/command-palette#32]
[Enter steps to reproduce below:]

1. press shift-cmd-p 

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.1
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.34.0

### Stack Trace

Uncaught SyntaxError: Failed to execute 'webkitMatchesSelector' on 'Element': 'coffee-lint:lint-current-file' is not a valid selector.

```
At /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:117

Error: Failed to execute 'webkitMatchesSelector' on 'Element': 'coffee-lint:lint-current-file' is not a valid selector.
  at Error (native)
  at CommandRegistry.module.exports.CommandRegistry.findCommands (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:117:121)
  at CommandPaletteView.module.exports.CommandPaletteView.show (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:70:32)
  at CommandPaletteView.module.exports.CommandPaletteView.toggle (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:49:21)
  at atom-workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:21:21)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -9:03.2 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
  2x -9:00.6 core:backspace (atom-text-editor.editor.mini)
     -8:57.8 editor:consolidate-selections (atom-text-editor.editor.mini)
     -8:57.8 core:cancel (atom-text-editor.editor.mini)
     -8:50.8 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -8:47.9 editor:consolidate-selections (atom-text-editor.editor.mini)
     -8:47.9 core:cancel (atom-text-editor.editor.mini)
     -3:40.3 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -3:38.2 editor:consolidate-selections (atom-text-editor.editor.mini)
     -3:38.2 core:cancel (atom-text-editor.editor.mini)
     -3:37.3 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -3:35.7 editor:consolidate-selections (atom-text-editor.editor.mini)
     -3:35.7 core:cancel (atom-text-editor.editor.mini)
  9x -3:15.6 core:backspace (atom-text-editor.editor.mini)
  3x -0:15.6 command-palette:toggle (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "composer",
      "behat-atom",
      "ruby-block-converter"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-lint, v0.20.1
atom-runner, v2.3.0
autocomplete-plus, v2.3.0
coffee-lint, v0.7.3
git-log, v0.3.0
git-tab-status, v1.5.3
jsonlint, v1.0.1
language-twig, v1.5.2
linter, v0.12.0
linter-csslint, v0.0.11
linter-flow, v0.1.3
linter-haml, v0.1.1
linter-php, v0.0.11
linter-rubocop, v0.2.2
linter-ruby, v0.1.4
linter-scss-lint, v0.0.14
markdown-format, v2.5.0
php-twig, v3.0.0
phpunit, v1.0.9
phpunit-snippets, v0.1.0
preview-plus, v1.1.19
project-manager, v1.15.5
rsense, v0.6.0
save-session, v0.11.5
script, v2.18.0
slash-closer, v0.7.1
symbols-tree-view, v0.6.1
symfony-snippets, v0.3.0
sync-settings, v0.2.1

# Dev
No dev packages
```

**Comment by lmartins** [comment]
Getting a similar error when trying to invoke the command pallete, except it says:
```
Uncaught SyntaxError Failed to execute
'webkitMatchesSelector' on 'Element': '0' is not a valid
selector
```

From this point I have to quit and reopen Atom to be able to do anything.
