### ISSUE TITLE
Uncaught TypeError: undefined is not a function: Move to previous Word

### ISSUE THREAD

**Issue by kalanosh** [atom/command-palette#41]
1. Open command palette
1. Type previous word
1. Select Editor: Move to previous Word

**Atom Version**: 0.200.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.36.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\src\text-editor-element.js:345

TypeError: undefined is not a function
  at TextEditor.atom.commands.add.stopEventPropagation.editor:move-to-previous-word (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\src\text-editor-element.js:345:19)
  at atom-text-editor.newCommandListeners.(anonymous function) (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\src\text-editor-element.js:286:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Kalanosh\AppData\Local\atom\app-0.200.0\resources\app.asar\src\window-event-handler.js:178:20)

```

### Commands

```
     -0:51.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  5x -0:48.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:44.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:44.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:44.4.0 editor:move-to-previous-word (atom-text-editor.editor)
     -0:41.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:41 core:move-down (atom-text-editor.editor.is-focused)
     -0:12.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 17x -0:10.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:08.2.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:07.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:05.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:02.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.6.0 editor:move-to-previous-word (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
linter, v0.12.4
linter-coffeelint, v0.2.3
linter-csslint, v0.0.12
linter-htmlhint, v0.0.15
linter-jshint, v0.1.4
linter-less, v0.4.0
linter-php, v0.0.12
linter-pylint, v0.2.1
linter-rubocop, v0.2.6
script, v2.23.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@kevinsawicki @nathansobo I was able to reproduce this. From what I can tell, there is no `moveToPreviousWord` method on the text editor, nor anywhere else. A quick grep over the history makes me suspect that such a method existed at some point somewhere, but was removed. Perhaps this command was supposed to be removed as well?

**Comment by izuzak** [comment]
And thanks for reporting this, @kalanosh :bow:

**Comment by izuzak** [comment]
Ahh, just noticed that @jberube reported this in https://github.com/atom/command-palette/issues/25#issuecomment-74359970 a few months ago. Sorry for missing that, @jberube!

**Comment by kalanosh** [comment]
Hey i was about to say, it was already reported. But it seems it was reported and closed, maybe after they added their comment? So I opened a new one cause it seems issue get addressed quickly. This one was back in December. So I figured it got lost cause the errors were the same but me and @jberune error reproduced different from the OP of the issue. 

Hope that was okay.

**Comment by izuzak** [comment]
@kalanosh Yep, I think we just didn't notice the errors in the other issue after it was closed, and these reports are different from what was originally reported in the other issue. Thanks again for opening this one!
