### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by cerberillo** [atom/command-palette#42]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.200.0
**System**: Mac OS X 10.10.3
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.36.0

### Stack Trace

Uncaught TypeError: Cannot read property 'call' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238

TypeError: Cannot read property 'call' of undefined
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)
```

### Commands

```
     -0:40.2.0 core:delete (atom-text-editor.editor.is-focused)
  6x -0:40.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:39.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:39 core:delete (atom-text-editor.editor.is-focused)
     -0:38.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:37.9.0 core:delete (atom-text-editor.editor.is-focused)
     -0:37.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:37.7.0 core:delete (atom-text-editor.editor.is-focused)
     -0:34.1.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:21.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:05.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -0:04.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:04.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.5.0 markdown-pdf:convert (atom-text-editor.editor)
     -0:00.5.0 core:move-down (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "file-icons"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-haml, v0.20.0
language-lua, v0.9.3
markdown-pdf, v1.3.6
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by izuzak** [comment]
This is a problem in the markdown-pdf package which is registering a command with an `undefined` callback (see https://github.com/travs/markdown-pdf/issues/54). 

Basically, typing this in the console will reproduce the problem:

```coffee
atom.commands.add('atom-workspace', 'markdown-pdf:convert', undefined);
atom.commands.dispatch(atom.views.getView(atom.workspace), "markdown-pdf:convert")
```

@nathansobo @kevinsawicki Would be great if we could either a) prevent these notification from happening (e.g. by ignoring commands with invalid callbacks and logging a warning to the console) or b) making the notification point to the correct package somehow. Does one of these two sound like a good idea to you? :thought_balloon:

**Comment by nathansobo** [comment]
I'd like for the command registry to just blow up immediately if registering a callback where `typeof callback isnt "function"`. #good-first
