### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by ashiato45** [atom/command-palette#43]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Unknown Windows Version
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.36.0

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At /C:/Users/tak/github/sumatra-forwardsearch/lib/sumatra-forwardsearch.coffee:41

ReferenceError: path is not defined
  at Object.module.exports.SumatraForwardsearch.forwardsearch (C:\Users\tak\github\sumatra-forwardsearch\lib\sumatra-forwardsearch.coffee:29:15)
  at atom-workspace.subscriptions.add.atom.commands.add.sumatra-forwardsearch:forwardseach (C:\Users\tak\github\sumatra-forwardsearch\lib\sumatra-forwardsearch.coffee:18:102)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\tak\AppData\Local\atom\app-0.201.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\tak\AppData\Local\atom\app-0.201.0\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\tak\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\tak\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\tak\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\tak\AppData\Local\atom\app-0.201.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\tak\AppData\Local\atom\app-0.201.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\tak\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\tak\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\tak\AppData\Local\atom\app-0.201.0\resources\app.asar\src\window-event-handler.js:178:20)

```

### Commands

```
     -0:16.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -0:14.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:13 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.9.0 sumatra-forwardsearch:forwardsearch (atom-text-editor.editor)
     -0:07.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.7.0 sumatra-forwardsearch:forwardseach (atom-text-editor.editor)
     -0:03.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:02.3.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "convert-to-utf8",
      "autocomplete-plus",
      "emacs-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ashiato45-atom, v0.0.0
atomic-emacs, v0.5.1
ide-haskell, v0.4.2
japanese-wrap, v0.2.7
language-batch, v0.3.3
language-haskell, v1.0.0
language-latex, v0.6.1
sumatra-forwardsearch, v0.7.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
That's a bug in your package, I believe -- you need a `path = require("path")` at the top of your [file](https://github.com/ashiato45/sumatra-forwardsearch/blob/master/lib/sumatra-forwardsearch.coffee).

The fact that it's reported as a problem in the command palette is probably a bug in https://github.com/atom/notifications -- I'll open an issue there to track this.

**Comment by ashiato45** [comment]
I fixed with your solution.  Thanks!
