### ISSUE TITLE
Failed to activate the Clean2 package

### ISSUE THREAD

**Issue by msimanga** [atom/command-palette#57]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.36.0

### Stack Trace

Failed to activate the Clean2 package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (C:\Development\atom\clean2\lib\clean.coffee:82:23)
  at Package.module.exports.Package.activateNow (C:\Users\mmsimang\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:243:19)
  at C:\Users\mmsimang\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:836:25
  at Emitter.module.exports.Emitter.emit (C:\Users\mmsimang\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\mmsimang\AppData\Local\atom\app-1.0.7\resources\app.asar\src\command-registry.js:222:20)
  at C:\Users\mmsimang\AppData\Local\atom\app-1.0.7\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\mmsimang\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\mmsimang\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\mmsimang\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\mmsimang\AppData\Local\atom\app-1.0.7\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\mmsimang\AppData\Local\atom\app-1.0.7\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\mmsimang\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\mmsimang\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\mmsimang\AppData\Local\atom\app-1.0.7\resources\app.asar\src\window-event-handler.js:177:20)

```

### Commands

```
     -0:10.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:05.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.5.0 clean2:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ],
    "projectHome": "C:\\Development"
  }
}
```

### Installed Packages

```coffee
# User
Clean2, v0.14.0

# Dev
No dev packages
```

**Comment by msimanga** [comment]
Issue automatically created by Atom feedback. Haven't done enough analysis to deem this an issue.
