### ISSUE TITLE
Uncaught ReferenceError: Grim is not defined

### ISSUE THREAD

**Issue by antogerva** [atom/command-palette#62]
[Enter steps to reproduce below:]

1. shift-enter-p
2. press : then w, then enter

**Atom Version**: 1.2.4
**System**: Microsoft Windows 10 Home
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.36.0

### Stack Trace

Uncaught ReferenceError: Grim is not defined

```
At C:\Users\user\AppData\Local\atom\app-1.2.4\resources\app.asar\src\register-default-commands.js:161

ReferenceError: Grim is not defined
    at atom-workspace.commandRegistry.add.window:log-deprecation-warnings (C:\Users\user\AppData\Local\atom\app-1.2.4\resources\app.asar\src\register-default-commands.js:161:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\user\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\user\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\user\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\user\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\user\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\user\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\user\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\user\AppData\Local\atom\app-1.2.4\resources\app.asar\src\window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.2.4\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -4:38.6.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -4:37.3.0 core:undo (atom-text-editor.editor.is-focused)
  2x -4:32 core:save (atom-text-editor.editor.is-focused)
  2x -4:14 core:undo (atom-text-editor.editor.is-focused)
     -4:13 core:save (atom-text-editor.editor.is-focused)
  3x -2:54.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:53.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -2:12.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -1:47.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:45.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:21.4.0 command-palette:toggle (div.panels)
  4x -0:16.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:08.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.2.0 window:log-deprecation-warnings (div.panels)
     -0:05.8.0 core:confirm (div.panels)
     -0:01.0 fuzzy-finder:toggle-file-finder (div.panels)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "Tern"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-beautify, v0.28.19
atom-typescript, v7.14.1
language-batch, v0.3.3
linter, v1.11.3
minimap, v4.16.2
react, v0.12.10

# Dev
No dev packages
```

**Comment by Tyriar** [comment]
Just hit this, Atom 1.2.4 on Ubuntu 12.04.

My repro:

1. <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>P</kbd>
2. `"Log depre"`
3. <kbd>enter</kbd>

**Comment by 50Wliu** [comment]
Confirmed on 1.5.0-dev-d6fa46a, Windows 10 x64.
