### ISSUE TITLE
Uncaught Error: Pane items must be objects. Attempted to add item undefined.

### ISSUE THREAD

**Issue by mcastilho** [atom/command-palette#67]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.38.0

### Stack Trace

Uncaught Error: Pane items must be objects. Attempted to add item undefined.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:450

Error: Pane items must be objects. Attempted to add item undefined.
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:450:15)
    at Pane.module.exports.Pane.moveItemToPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:610:19)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:898:14)
    at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:856:19)
    at atom-pane.commandRegistry.add.pane:split-right-and-move-active-item (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:267:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -0:25.8.0 pane:move-item-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:23.6.0 pane:move-item-left (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:23.3.0 pane:move-item-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:18.2.0 editor:select-to-next-subword-boundary (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:17.7.0 editor:select-to-end-of-word (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:16.9.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:16.3.0 editor:select-to-end-of-line (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:14.4.0 command-palette:toggle (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -0:11.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:10.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10.5.0 pane:split-right (atom-text-editor.editor.vim-mode.normal-mode)
     -0:07.5.0 command-palette:toggle (atom-pane.pane.active)
 12x -0:05.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 pane:split-right-and-move-active-item (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai-seti"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-go, v1.1.0
builder-go, v1.0.0
editorconfig, v1.4.1
file-icons, v1.7.11
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
go-signature-statusbar, v1.0.3
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
highlight-line, v0.11.1
highlight-selected, v0.11.2
language-babel, v2.20.10
language-docker, v1.1.6
language-protobuf, v0.5.0
last-cursor-position, v0.9.0
linter, v1.11.4
monokai-seti, v0.7.0
navigator-godef, v1.0.3
pretty-json, v1.1.0
react, v0.15.0
react-es6-snippets, v0.3.0
redux-snippets, v0.2.2
tester-go, v1.0.4
vim-mode, v0.65.0
vim-surround, v0.8.1
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Closing in favor of atom/atom#11189 - feel free to subscribe there for updates.
