### ISSUE TITLE
Uncaught TypeError: this.getActivePaneContainer(...).activateNextPane is not a function

### ISSUE THREAD

**Issue by jasonrudolph** [atom/command-palette#79]
1. Open a file
2. Open the tree view
3. While the tree view has focus, trigger the `window:focus-next-pane` command via the command palette
4. Observe exception

### Demo

![demo](https://cloud.githubusercontent.com/assets/2988/25817789/60b9d8d6-33f6-11e7-9cfa-1753326c5c04.gif)

**Atom**: 1.17.0-beta5 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package 0.40.4

### Stack Trace

Uncaught TypeError: this.getActivePaneContainer(...).activateNextPane is not a function

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/workspace.js:1559

TypeError: this.getActivePaneContainer(...).activateNextPane is not a function
    at Workspace.activateNextPane (/Applications/Atom Beta.app/Contents/Resources/app/src/workspace.js:1559:1)
    at atom-workspace.window:focus-next-pane (/Applications/Atom Beta.app/Contents/Resources/app/src/register-default-commands.js:168:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:1
    at Object.didConfirmSelection (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:106:1)
    at SelectListView.confirmSelection (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:313:1)
    at HTMLDivElement.core:confirm (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:81:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:21.7.0 core:move-down (input.hidden-input)
     -0:21 core:confirm (input.hidden-input)
     -0:21 window:focus-next-pane (input.hidden-input)
  3x -0:20.4.0 core:move-down (input.hidden-input)
  3x -0:19.9.0 core:move-up (input.hidden-input)
     -0:19 command-palette:toggle (input.hidden-input)
     -0:17.4.0 core:backspace (input.hidden-input)
     -0:16.2.0 core:confirm (input.hidden-input)
     -0:16.2.0 window:focus-previous-pane (input.hidden-input)
  2x -0:15.6.0 core:move-down (input.hidden-input)
  3x -0:15.3.0 core:move-up (input.hidden-input)
     -0:14 tree-view:toggle (input.hidden-input)
  4x -0:13.1.0 core:move-up (div.tool-panel.tree-view)
     -0:12 command-palette:toggle (div.tool-panel.tree-view)
     -0:10.5.0 core:confirm (input.hidden-input)
     -0:10.5.0 window:focus-next-pane (div.tool-panel.tree-view)
```

### Non-Core Packages

```
activate-power-mode 1.4.0
advanced-open-file 0.16.6
atom-beautify 0.29.24
atom-fuzzy-grep 0.16.0
atom-math 0.0.9
autocomplete-emojis 2.5.0
branch-status 0.8.3
bug-free-palm-tree 0.2.1
file-icons 2.1.4
git-time-machine 1.5.9
github 0.0.2
highlight-line 0.12.0
indent-guide-improved 1.4.12
jumpy 3.1.3
language-applescript 0.3.0
language-gherkin 1.0.4
language-lua 0.9.11
linter 2.1.4
linter-rubocop 2.1.1
markdown-scroll-sync 2.1.2
maximize-panes 0.2.0
move-panes 0.2.0
nvatom 0.11.0
packages undefined
revert-buffer 0.5.0
script 3.14.1
shell-it 0.2.1
sholight 0.2.0
significant-other 0.2.0
smalls 0.3.0
sort-lines 0.12.0
Sublime-Style-Column-Selection 1.7.4
tablr 1.8.3
toggle-markdown-task 0.6.0
toggle-quotes 1.0.1
transform 0.4.0
```

**Comment by jasonrudolph** [comment]
I've observed this issue in the current beta (1.17.0-beta5), but I cannot reproduce it in the current stable release (1.16.0). Could this problem be related to the fact that the beta renders the tree view in a [Dock](https://github.com/atom/atom/blob/e0309883bbdaf75973689961ddbc75333cd5c46e/src/dock.js)?

**Comment by 50Wliu** [comment]
Moving to atom/atom because it belongs there (#14442).
