### ISSUE TITLE
Failed to reload the command-palette package stylesheets

### ISSUE THREAD

**Issue by dylan-k** [atom/command-palette#82]
**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package 0.40.4

### Stack Trace

Failed to reload the command-palette package stylesheets

```
At EACCES: permission denied, open '/home/dylan/.atom/compile-cache/less/afb3afa445f73bc661a5e2e7a6b1b41ae44995ee/content/a018f10dcb9bdf999cb3f0113ca668f6374c42d6/command-palette.json'

Error: EACCES: permission denied, open '/home/dylan/.atom/compile-cache/less/afb3afa445f73bc661a5e2e7a6b1b41ae44995ee/content/a018f10dcb9bdf999cb3f0113ca668f6374c42d6/command-palette.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Proxy.writeFileSync (/opt/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:298:29)
    at LessCache.module.exports.LessCache.writeJson (/opt/atom/resources/app/node_modules/less-cache/lib/less-cache.js:212:23)
    at LessCache.module.exports.LessCache.putCachedCss (/opt/atom/resources/app/node_modules/less-cache/lib/less-cache.js:300:18)
    at LessCache.module.exports.LessCache.cssForFile (/opt/atom/resources/app/node_modules/less-cache/lib/less-cache.js:358:18)
    at LessCompileCache.module.exports.LessCompileCache.cssForFile (/opt/atom/resources/app/src/less-compile-cache.js:43:31)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/opt/atom/resources/app/src/theme-manager.js:302:39)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/opt/atom/resources/app/src/theme-manager.js:271:27)
    at /opt/atom/resources/app/src/package.js:545:60
    at Array.map (native)
    at Package.module.exports.Package.loadStylesheets (/opt/atom/resources/app/src/package.js:543:65)
    at Package.module.exports.Package.reloadStylesheets (/opt/atom/resources/app/src/package.js:858:20)
    at PackageManager.module.exports.PackageManager.reloadActivePackageStyleSheets (/opt/atom/resources/app/src/package-manager.js:786:24)
    at /opt/atom/resources/app/src/theme-manager.js:29:47
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /opt/atom/resources/app/src/theme-manager.js:364:35
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### Commands

```
  2x -1:31.3.0 core:paste (input.hidden-input)
     -0:57.5.0 intentions:highlight (input.hidden-input)
     -0:57 command-palette:toggle (input.hidden-input)
  2x -0:54.3.0 core:move-down (input.hidden-input)
     -0:51 core:confirm (input.hidden-input)
     -0:51 sync-settings:restore (input.hidden-input)
     -0:28.1.0 intentions:highlight (input.hidden-input)
     -0:28.1.0 command-palette:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-monokai 0.10.9 
atom-wrap-in-tag 0.6.0 
auto-detect-indentation 1.3.0 
autocomplete-modules 1.6.10 
base16-darker-high-contrast-syntax 1.5.1-0 
broadcast 0.4.0 
busy-signal 1.4.3 
date 1.2.2 
file-types 0.5.5 
fountain 0.5.4 
gist 0.4.0 
git-plus 7.9.3 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hyper-ui 0.1.3 
intentions 1.1.2 
jekyll 2.1.0 
language-asp 1.0.0 
language-asp-html 0.3.0 
language-aspx 0.5.0 
language-liquid 0.5.1 
language-markdown 0.23.0 
language-vb 0.1.0-pre1 
linter 2.1.4 
linter-ui-default 1.6.1 
linter-write-good 0.9.0 
markdown-helpers 0.3.0 
markdown-writer 2.6.5 
newbound-dark-syntax 1.1.0 
one-black-syntax 1.11.0 
one-o-eight-syntax 0.28.2 
open-on-bitbucket 0.4.0 
open-plus 0.10.1 
open-recent 5.0.0 
predawn-syntax 1.0.4 
project-manager 3.3.5 
pubster-syntax 3.0.1 
Remote-FTP 0.10.7 
set-syntax 0.3.2 
seti-syntax 1.0.1 
seti-ui 1.8.0 
SFTP-deployment 1.0.2 
simple-drag-drop-text 0.3.4 
sort-lines 0.14.0 
split-diff 1.4.1 
sync-settings 0.8.1 
tag 0.5.0 
tasks 2.6.6 
text-manipulation 0.6.0 
today 0.2.0 
wordcount 2.10.4 
Zen 0.18.0 
zooce-syntax 1.0.1 
```

**Comment by rsese** [comment]
> At EACCES: permission denied, open '/home/dylan/.atom/compile-cache/less/afb3afa445f73bc661a5e2e7a6b1b41ae44995ee/content/a018f10dcb9bdf999cb3f0113ca668f6374c42d6/command-palette.json'

Can you check if the permissions for this file are correct?  

```
ls -l /home/dylan/.atom/compile-cache/less/afb3afa445f73bc661a5e2e7a6b1b41ae44995ee/content/a018f10dcb9bdf999cb3f0113ca668f6374c42d6/command-palette.json
```

I think on Ubuntu the user and group should just be your account name (or at least that's how it is on my Ubuntu vm).  If the permissions don't look right (e.g. the file is owned by `root`), you can change the permissions for the whole directory and everything in it:

```
sudo chown -R YOUR_USERNAME:YOUR_USERNAME ~/.atom
```

**Comment by dylan-k** [comment]
That did the trick.
