### ISSUE TITLE
Uncaught Error: Replacing non-existent child

### ISSUE THREAD

**Issue by JohaWeber** [atom/command-palette#84]
[Enter steps to reproduce:]

1. open new window via ctrl + shift + n
2. open project via project manager plugin
3. open file (js/html/css) with fuzzy finder via ctrl + p
4. toggle command palette
5. type in "pane: split left/down/right/up"

**Atom**: 1.19.0-beta6 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package 0.40.4

### Stack Trace

Uncaught Error: Replacing non-existent child

```
At C:\Users\Username\AppData\Local\atom\app-1.19.0-beta6\resources\app\src\pane-container.js:145

Error: Replacing non-existent child
    at PaneContainer.replaceChild (~/AppData/Local/atom/app-1.19.0-beta6/resources/app/src/pane-container.js:145:47)
    at Pane.module.exports.Pane.split (~/AppData/Local/atom/app-1.19.0-beta6/resources/app/src/pane.js:984:27)
    at Pane.module.exports.Pane.splitLeft (~/AppData/Local/atom/app-1.19.0-beta6/resources/app/src/pane.js:960:25)
    at HTMLElement.pane:split-left (~/AppData/Local/atom/app-1.19.0-beta6/resources/app/src/register-default-commands.js:252:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.0-beta6/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.19.0-beta6/resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.19.0-beta6/resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.19.0-beta6/resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (~/AppData/Local/atom/app-1.19.0-beta6/resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.0-beta6/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.19.0-beta6/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.19.0-beta6/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.19.0-beta6/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.19.0-beta6/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.19.0-beta6/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:36.9.0 project-manager:list-projects (input.hidden-input)
     -0:35.9.0 core:confirm (input.hidden-input)
     -0:35.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-predawn-syntax.theme-one-dark-ui)
     -0:33.8.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-predawn-syntax.theme-one-dark-ui)
     -0:30.9.0 core:move-down (input.hidden-input)
     -0:30.8.0 core:confirm (input.hidden-input)
     -0:18.2.0 project-manager:list-projects (input.hidden-input)
     -0:17.3.0 editor:consolidate-selections (input.hidden-input)
     -0:17.3.0 core:cancel (input.hidden-input)
     -0:16.8.0 intentions:highlight (input.hidden-input)
     -0:16.6.0 command-palette:toggle (input.hidden-input)
     -0:16.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-predawn-syntax.theme-one-dark-ui)
  2x -0:15.7.0 core:backspace (input.hidden-input)
  2x -0:14.2.0 core:move-down (input.hidden-input)
     -0:13.4.0 core:confirm (input.hidden-input)
     -0:13.4.0 pane:split-left (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.4 
atom-bracket-highlight 0.3.2 
atom-ternjs 0.18.3 
autocomplete-modules 1.6.10 
autocomplete-paths 1.0.5 
autocomplete-webpack 0.8.0 
autoupdate-packages 1.3.1 
bottom-dock 0.4.4 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.9 
grunt-manager 0.1.16 
intentions 1.1.5 
language-postcss 1.3.1 
language-powershell 4.0.0 
language-vue 0.23.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-js-standard 3.9.3 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.3 
minimap 4.29.3 
minimap-cursorline 0.2.0 
minimap-pigments 0.2.2 
multi-file-open 0.1.1 
pigments 0.40.1 
predawn-syntax 1.0.4 
predawn-ui 1.0.7 
project-manager 3.3.5 
set-syntax 0.3.2 
standard-formatter 2.8.0 
sync-settings 0.8.2 
```

**Comment by QuintinS** [comment]
+1
