### ISSUE TITLE
Uncaught TypeError: validateEventDispatches is not a function 

### ISSUE THREAD

**Issue by GuyMograbi** [atom/command-palette#93]
[Enter steps to reproduce:]

I am not sure how to reproduce this. 
Just installed this plugin and added my first command to run an express server. 

This also causes tabs in atom to not work properly - double clicking a file will open a tab, but the new tab will not be focused. I have to click it to focus on it. 

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: validateEventDispatches is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginUtils.js:97

TypeError: validateEventDispatches is not a function
    at Object.executeDispatchesInOrder (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginUtils.js:97:11)
    at executeDispatchesAndRelease (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginHub.js:43:28)
    at executeDispatchesAndReleaseTopLevel (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginHub.js:54:16)
    at Array.forEach (native)
    at forEachAccumulated (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/forEachAccumulated.js:24:15)
    at Object.processEventQueue (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginHub.js:254:13)
    at runEventQueueInBatch (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventEmitterMixin.js:17:24)
    at Object.handleTopLevel [as _handleTopLevel] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventEmitterMixin.js:27:11)
    at handleTopLevelImpl (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventListener.js:72:30)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/Transaction.js:143:26)
    at Object.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:32)
    at Object.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactUpdates.js:97:33)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventListener.js:147:26)
    at HTMLElement.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:117:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:927:33)
    at Workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1178:20)
    at Generator.next (<anonymous>)
    at step (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:11:279)
```

### Commands

```
     -5:53.9.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -5:51.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-runner 2.7.1 
gitkraken 0.4.3 
language-pug 0.0.21 
node-debugger 1.10.1 
platformio-ide-terminal 2.7.0 
process-palette 0.15.1 
```

**Comment by rsese** [comment]
Thanks for the report @GuyMograbi!

> I am not sure how to reproduce this.
> Just installed this plugin and added my first command to run an express server.

I'm guessing you're referring to atom-runner?  Also, it sounds like the error isn't reproducible for you?

If this is the case, I think the issue might be with https://github.com/lsegal/atom-runner.  You can file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
